---
- hosts: bastion_host
  gather_facts: no
  ##  become: true

  tasks:

   - name: "Download Red Hat ISO"
     get_url:
       url: "{{ iso_url }}"
       dest: "{{ org_iso }}"
       client_cert: /etc/pki/entitlement/2426331512878849778.pem
       client_key: /etc/pki/entitlement/2426331512878849778-key.pem
