---
- hosts: bastion_host
  gather_facts: no
  ##  become: true

  tasks:

   - name: "Find the name of the key file for accessing Red Hat CDN, we'll use this for downloading the ISO file"
     find:
       paths: /etc/pki/entitlement/
       patterns: '*-key.pem'
     register: rhcdn_key

   - name: "Find the name of the cert file for accessing Red Hat CDN, we'll use this for downloading the ISO file"
     find:
       paths: /etc/pki/entitlement/
       excludes: '-key'
       patterns: '*.pem'
     register: rhcdn_cert

   - debug: msg= "{{ rhcdn_key.stdout }}"

   - debug: msg= "{{ rhcdn_cert.stdout }}"
          
       #   - name: "Download Red Hat ISO"
       #     get_url:
       #       url: "{{ iso_url }}"
       #       dest: "{{ org_iso }}"
       #       client_cert: '/etc/pki/entitlement/"{{ rhcdn_cert }}"' #2426331512878849778.pem
       #       client_key: '/etc/pki/entitlement/"{{ rhcdn_key }}"'
