---
- hosts: bastion_host
  gather_facts: no

  tasks:
  - name: "Download Red Hat ISO"
    get_url:
       url: "{{ iso_url }}"
       dest: "{{ org_iso }}"
       client_cert: '/etc/pki/entitlement/2426331512878849778.pem' #'{{ rhcdn_cert.path }}'
       client_key: '/etc/pki/entitlement/2426331512878849778-key.pem' #'{{ rhcdn_key.path }}'


          #########################################
          #I should be debugging the use of find moduel instead of using file name
          #########################################

   #- name: "Find the name of the key file for accessing Red Hat CDN, we'll use this for downloading the ISO file"
      #find:
        #paths: /etc/pki/entitlement/
        #file_type: file
        #patterns: '*-key.pem'
      #register: rhcdn_key

   #- name: "Find the name of the cert file for accessing Red Hat CDN, we'll use this for downloading the ISO file"
     #find:
     #  paths: /etc/pki/entitlement/
     #  file_type: file
     #  excludes: '*-key.pem'
     #  patterns: '*.pem'
     #register: rhcdn_cert    
