---
- hosts: bastion_host
  gather_facts: no
  ##  become: true

  tasks:

   - name: Mount installation ISO read-only
     mount:
       path: "{{ mnt_dir }}"
       src:  "{{ org_iso }}"
       fstype: "iso9660"
       opts: loop,ro
       state: mounted
     become: true

