---
- hosts: bastion_host
  gather_facts: no
  ##  become: true

  tasks:

   - name: Mount installation ISO read-only
     mount:
       path: "{{ mnt_dir }}"
       src:  "{{ org_iso }}"
       fstype: "iso9660"
       opts: loop,ro
       state: mounted
     become: true

   - name: Create a directory if it does not exist
     file:
       path: "{{ wrk_dir }}"
       state: directory

   - name: Copy ISO content to workingdir (needs to run as root otherwise all files will change ownership)
     copy:
       src:  "{{ mnt_dir }}/"
       dest: "{{ wrk_dir }}/"
       remote_src: yes
     become: true

   - name: Unmount installation ISO
     mount:
       path: "{{ mnt_dir }}"
       state: unmounted
     become: true

   - name: "Create the file ks.cfg file"
     become: yes
     file:
       path: "{{ wrk_dir }}/ks.cfg"
       state: touch

   - name: "Fill the content of ks.cfg (beware of vars!)"
     become: yes
     blockinfile:
       path: "{{ wrk_dir }}/ks.cfg"
       block: |
         #version=RHEL8
         # Use graphical install
         #graphical
         shutdown
         eula --agreed
         %packages
         @^minimal-environment
         kexec-tools
         %end
         # Keyboard layouts
         keyboard --xlayouts='es'
         # System language
         lang en_US.UTF-8
         # Network information
         network  --bootproto=dhcp --device=enp1s0 --ipv6=auto --activate
         #network  --hostname=bastion.local
         # Run the Setup Agent on first boot
         firstboot --enable
         ignoredisk --only-use=vda
         autopart
         # Partition clearing information
         clearpart --none --initlabel
         # System timezone
         timezone Europe/Paris --isUtc --nontp
         # Root password
         rootpw --iscrypted $6$8y3IIZuF3En4OjsP$Z3JwrmZHGnUkmCuTpqWe9yC/HcrdNmhv6.ec6vDdVfaC8u1lVbohpgfHGn/O9OqMwHVK2JmXWlkgDl5xQS1Ov0
         %addon com_redhat_kdump --enable --reserve-mb='auto'
         %end
         %anaconda
         pwpolicy root --minlen=6 --minquality=1 --notstrict --nochanges --notempty
         pwpolicy user --minlen=6 --minquality=1 --notstrict --nochanges --emptyok
         pwpolicy luks --minlen=6 --minquality=1 --notstrict --nochanges --notempty
         %end

   - name: "Edit isolinux.cfg file so testing media is NOT the default option"
     become: yes
     #become_user: root
     lineinfile:
       path: "{{ wrk_dir }}/isolinux/isolinux.cfg"
       # String to Search
       regexp: "menu default"
       # State is set to Absent to remove if the Searching Line is found
       state: absent

   - name: "Create an entry in the boot menu (isolinux.cfg), which is the default option, allowing to boot using ks.cfg"
     become: yes
     blockinfile:
       path: "{{ wrk_dir }}/isolinux/isolinux.cfg"
       insertbefore: "label check\n"
       block: |
         label kickstart
           menu label ^Kickstart Installation of RHEL8.5
           menu default
           kernel vmlinuz
           append initrd=initrd.img inst.stage2=hd:LABEL=RHEL-8-5-0-BaseOS-x86_64 inst.ks=cdrom:/ks.cfg


   - name: "Delete the file grub.cfg"
     become: yes
     file:
       path: "{{ wrk_dir }}/EFI/BOOT/grub.cfg"
       state: absent

   - name: "Create the file grub.cfg (now it's a blank file)"
     become: yes
     file:
       path: "{{ wrk_dir }}/EFI/BOOT/grub.cfg"
       state: touch

   - name: "Fill the content of grub.cfg"
     become: yes
     blockinfile:
       path: "{{ wrk_dir }}/EFI/BOOT/grub.cfg"
       block: |
         ### BEGIN /etc/grub.d/10_linux ###
         menuentry 'Install Red Hat Enterprise Linux 8.5' --class fedora --class gnu-linux --class gnu --class os {
         linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=RHEL-8-5-0-BaseOS-x86_64 inst.ks=cdrom:/ks.cfg
         initrdefi /images/pxeboot/initrd.img
         }




